version: '3.7'
services:
  app:
    build:
      context: ./app
    volumes:
      - ./app/arrogancia/:/go/src/arrogancia
    ports:
      - 28080:8080
    env_file:
     # 指定しないと読んでくれない
     - ./.env
    depends_on:
      - db
  db:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - 23306:3306
    volumes:
      - ./etc/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./etc/mysql/ddl/:/docker-entrypoint-initdb.d/
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake

